/*
 * oxauth_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package fidou2f_pkg

import "oxauth_lib/configuration_pkg"
import "oxauth_lib/models_pkg"

/*
 * Interface for the FIDOU2F_IMPL
 */
type FIDOU2F interface {
    GetFidoU2fAuthentication (string, *string, *string, *string) (*models_pkg.AuthenticateRequestMessage, error)

    PostFidoU2fAuthentication (*models_pkg.GetClientTokenParams) (*models_pkg.AuthenticateStatus, error)

    GetFidoConfiguration () (*models_pkg.U2fConfiguration, error)

    GetFidoU2fRegistration (string, *string, *string, *string) (*models_pkg.RegisterRequestMessage, error)

    PostFidoU2fRegistration (*models_pkg.RegisterSiteParams) (*models_pkg.RegisterStatus, error)
}

/*
 * Factory for the FIDOU2F interaface returning FIDOU2F_IMPL
 */
func NewFIDOU2F(config configuration_pkg.CONFIGURATION) *FIDOU2F_IMPL {
    client := new(FIDOU2F_IMPL)
    client.config = config
    return client
}