// Code generated by go-swagger; DO NOT EDIT.

package token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/gojans/go-swagger/gluu-4.2.1/oxauth/models"
)

// GetIntrospectionReader is a Reader for the GetIntrospection structure.
type GetIntrospectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIntrospectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIntrospectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetIntrospectionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetIntrospectionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetIntrospectionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetIntrospectionOK creates a GetIntrospectionOK with default headers values
func NewGetIntrospectionOK() *GetIntrospectionOK {
	return &GetIntrospectionOK{}
}

/*GetIntrospectionOK handles this case with default header values.

OK
*/
type GetIntrospectionOK struct {
	Payload *models.IntrospectionResponse
}

func (o *GetIntrospectionOK) Error() string {
	return fmt.Sprintf("[GET /introspection][%d] getIntrospectionOK  %+v", 200, o.Payload)
}

func (o *GetIntrospectionOK) GetPayload() *models.IntrospectionResponse {
	return o.Payload
}

func (o *GetIntrospectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IntrospectionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIntrospectionBadRequest creates a GetIntrospectionBadRequest with default headers values
func NewGetIntrospectionBadRequest() *GetIntrospectionBadRequest {
	return &GetIntrospectionBadRequest{}
}

/*GetIntrospectionBadRequest handles this case with default header values.

Error codes for introspection endpoint.
*/
type GetIntrospectionBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetIntrospectionBadRequest) Error() string {
	return fmt.Sprintf("[GET /introspection][%d] getIntrospectionBadRequest  %+v", 400, o.Payload)
}

func (o *GetIntrospectionBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetIntrospectionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIntrospectionUnauthorized creates a GetIntrospectionUnauthorized with default headers values
func NewGetIntrospectionUnauthorized() *GetIntrospectionUnauthorized {
	return &GetIntrospectionUnauthorized{}
}

/*GetIntrospectionUnauthorized handles this case with default header values.

Unauthorized access request.
*/
type GetIntrospectionUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *GetIntrospectionUnauthorized) Error() string {
	return fmt.Sprintf("[GET /introspection][%d] getIntrospectionUnauthorized  %+v", 401, o.Payload)
}

func (o *GetIntrospectionUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetIntrospectionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetIntrospectionInternalServerError creates a GetIntrospectionInternalServerError with default headers values
func NewGetIntrospectionInternalServerError() *GetIntrospectionInternalServerError {
	return &GetIntrospectionInternalServerError{}
}

/*GetIntrospectionInternalServerError handles this case with default header values.

Internal error occured. Please check log file for details.
*/
type GetIntrospectionInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetIntrospectionInternalServerError) Error() string {
	return fmt.Sprintf("[GET /introspection][%d] getIntrospectionInternalServerError  %+v", 500, o.Payload)
}

func (o *GetIntrospectionInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetIntrospectionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
