/*
 * oxauth_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package jwkjsonwebkeysetjwks_pkg

import "oxauth_lib/configuration_pkg"
import "oxauth_lib/models_pkg"

/*
 * Interface for the JWKJSONWEBKEYSETJWKS_IMPL
 */
type JWKJSONWEBKEYSETJWKS interface {
    GetJwks () (*models_pkg.WebKeysConfiguration, error)
}

/*
 * Factory for the JWKJSONWEBKEYSETJWKS interaface returning JWKJSONWEBKEYSETJWKS_IMPL
 */
func NewJWKJSONWEBKEYSETJWKS(config configuration_pkg.CONFIGURATION) *JWKJSONWEBKEYSETJWKS_IMPL {
    client := new(JWKJSONWEBKEYSETJWKS_IMPL)
    client.config = config
    return client
}