/*
 * oxauth_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package umausermanagedaccess_pkg

import "oxauth_lib/configuration_pkg"
import "oxauth_lib/models_pkg"

/*
 * Interface for the UMAUSERMANAGEDACCESS_IMPL
 */
type UMAUSERMANAGEDACCESS interface {
    GetUmaGatherClaims (*string, *string, *string, *string, *bool, *bool) (error)

    PostUmaGatherClaims (*string, *string, *string, *string, *bool, *bool) (error)

    GetUma2Configuration () (*models_pkg.Uma2ConfigurationResponse, error)

    CreateHostRsrcPr (string, string, []string, map[string]string) ([]*models_pkg.UmaPermissionList, error)
}

/*
 * Factory for the UMAUSERMANAGEDACCESS interaface returning UMAUSERMANAGEDACCESS_IMPL
 */
func NewUMAUSERMANAGEDACCESS(config configuration_pkg.CONFIGURATION) *UMAUSERMANAGEDACCESS_IMPL {
    client := new(UMAUSERMANAGEDACCESS_IMPL)
    client.config = config
    return client
}