/*
 * oxauth_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package sessionmanagement_pkg

import "oxauth_lib/configuration_pkg"
import "oxauth_lib/models_pkg"

/*
 * Interface for the SESSIONMANAGEMENT_IMPL
 */
type SESSIONMANAGEMENT interface {
    GetSessionStatus () (*models_pkg.SessionStateObject, error)

    CreateRevokeSession (string, string) (error)

    GetEndSession (*string, *string, *string, *string) (error)
}

/*
 * Factory for the SESSIONMANAGEMENT interaface returning SESSIONMANAGEMENT_IMPL
 */
func NewSESSIONMANAGEMENT(config configuration_pkg.CONFIGURATION) *SESSIONMANAGEMENT_IMPL {
    client := new(SESSIONMANAGEMENT_IMPL)
    client.config = config
    return client
}