// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SessionStateObject SessionStateObject
//
// swagger:model SessionStateObject
type SessionStateObject struct {

	// specifies the time at which session was authenticated.
	AuthTime int32 `json:"auth_time,omitempty"`

	// custom state
	CustomState string `json:"custom_state,omitempty"`

	// String that represents the End-User's login state at the OP. It MUST NOT contain the space (\" \") character.
	State string `json:"state,omitempty"`
}

// Validate validates this session state object
func (m *SessionStateObject) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SessionStateObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SessionStateObject) UnmarshalBinary(b []byte) error {
	var res SessionStateObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
