// Code generated by go-swagger; DO NOT EDIT.

package registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBcDeviceRegistrationParams creates a new BcDeviceRegistrationParams object
// with the default values initialized.
func NewBcDeviceRegistrationParams() *BcDeviceRegistrationParams {
	var ()
	return &BcDeviceRegistrationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBcDeviceRegistrationParamsWithTimeout creates a new BcDeviceRegistrationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBcDeviceRegistrationParamsWithTimeout(timeout time.Duration) *BcDeviceRegistrationParams {
	var ()
	return &BcDeviceRegistrationParams{

		timeout: timeout,
	}
}

// NewBcDeviceRegistrationParamsWithContext creates a new BcDeviceRegistrationParams object
// with the default values initialized, and the ability to set a context for a request
func NewBcDeviceRegistrationParamsWithContext(ctx context.Context) *BcDeviceRegistrationParams {
	var ()
	return &BcDeviceRegistrationParams{

		Context: ctx,
	}
}

// NewBcDeviceRegistrationParamsWithHTTPClient creates a new BcDeviceRegistrationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewBcDeviceRegistrationParamsWithHTTPClient(client *http.Client) *BcDeviceRegistrationParams {
	var ()
	return &BcDeviceRegistrationParams{
		HTTPClient: client,
	}
}

/*BcDeviceRegistrationParams contains all the parameters to send to the API endpoint
for the bc device registration operation typically these are written to a http.Request
*/
type BcDeviceRegistrationParams struct {

	/*DeviceRegistrationToken
	  OAuth 2.0 Client Identifier valid at the Authorization Serve

	*/
	DeviceRegistrationToken string
	/*IDTokenHint
	  An ID Token previously issued to the Client by the OpenID Provider being passed back as a hint to identify the end-user for whom the device registration is being requested.

	*/
	IDTokenHint string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the bc device registration params
func (o *BcDeviceRegistrationParams) WithTimeout(timeout time.Duration) *BcDeviceRegistrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bc device registration params
func (o *BcDeviceRegistrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bc device registration params
func (o *BcDeviceRegistrationParams) WithContext(ctx context.Context) *BcDeviceRegistrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bc device registration params
func (o *BcDeviceRegistrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bc device registration params
func (o *BcDeviceRegistrationParams) WithHTTPClient(client *http.Client) *BcDeviceRegistrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bc device registration params
func (o *BcDeviceRegistrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceRegistrationToken adds the deviceRegistrationToken to the bc device registration params
func (o *BcDeviceRegistrationParams) WithDeviceRegistrationToken(deviceRegistrationToken string) *BcDeviceRegistrationParams {
	o.SetDeviceRegistrationToken(deviceRegistrationToken)
	return o
}

// SetDeviceRegistrationToken adds the deviceRegistrationToken to the bc device registration params
func (o *BcDeviceRegistrationParams) SetDeviceRegistrationToken(deviceRegistrationToken string) {
	o.DeviceRegistrationToken = deviceRegistrationToken
}

// WithIDTokenHint adds the iDTokenHint to the bc device registration params
func (o *BcDeviceRegistrationParams) WithIDTokenHint(iDTokenHint string) *BcDeviceRegistrationParams {
	o.SetIDTokenHint(iDTokenHint)
	return o
}

// SetIDTokenHint adds the idTokenHint to the bc device registration params
func (o *BcDeviceRegistrationParams) SetIDTokenHint(iDTokenHint string) {
	o.IDTokenHint = iDTokenHint
}

// WriteToRequest writes these params to a swagger request
func (o *BcDeviceRegistrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param device_registration_token
	frDeviceRegistrationToken := o.DeviceRegistrationToken
	fDeviceRegistrationToken := frDeviceRegistrationToken
	if fDeviceRegistrationToken != "" {
		if err := r.SetFormParam("device_registration_token", fDeviceRegistrationToken); err != nil {
			return err
		}
	}

	// form param id_token_hint
	frIDTokenHint := o.IDTokenHint
	fIDTokenHint := frIDTokenHint
	if fIDTokenHint != "" {
		if err := r.SetFormParam("id_token_hint", fIDTokenHint); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
