// Code generated by go-swagger; DO NOT EDIT.

package registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/gojans/go-swagger/gluu-4.2.1/oxauth/models"
)

// NewPostRegisterParams creates a new PostRegisterParams object
// with the default values initialized.
func NewPostRegisterParams() *PostRegisterParams {
	var ()
	return &PostRegisterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRegisterParamsWithTimeout creates a new PostRegisterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRegisterParamsWithTimeout(timeout time.Duration) *PostRegisterParams {
	var ()
	return &PostRegisterParams{

		timeout: timeout,
	}
}

// NewPostRegisterParamsWithContext creates a new PostRegisterParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRegisterParamsWithContext(ctx context.Context) *PostRegisterParams {
	var ()
	return &PostRegisterParams{

		Context: ctx,
	}
}

// NewPostRegisterParamsWithHTTPClient creates a new PostRegisterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRegisterParamsWithHTTPClient(client *http.Client) *PostRegisterParams {
	var ()
	return &PostRegisterParams{
		HTTPClient: client,
	}
}

/*PostRegisterParams contains all the parameters to send to the API endpoint
for the post register operation typically these are written to a http.Request
*/
type PostRegisterParams struct {

	/*Body*/
	Body *models.RegisterParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post register params
func (o *PostRegisterParams) WithTimeout(timeout time.Duration) *PostRegisterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post register params
func (o *PostRegisterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post register params
func (o *PostRegisterParams) WithContext(ctx context.Context) *PostRegisterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post register params
func (o *PostRegisterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post register params
func (o *PostRegisterParams) WithHTTPClient(client *http.Client) *PostRegisterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post register params
func (o *PostRegisterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post register params
func (o *PostRegisterParams) WithBody(body *models.RegisterParams) *PostRegisterParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post register params
func (o *PostRegisterParams) SetBody(body *models.RegisterParams) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRegisterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
