// Code generated by go-swagger; DO NOT EDIT.

package jwk_json_web_key_set_j_w_ks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewJWKSParams creates a new JWKSParams object
// with the default values initialized.
func NewJWKSParams() *JWKSParams {

	return &JWKSParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJWKSParamsWithTimeout creates a new JWKSParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJWKSParamsWithTimeout(timeout time.Duration) *JWKSParams {

	return &JWKSParams{

		timeout: timeout,
	}
}

// NewJWKSParamsWithContext creates a new JWKSParams object
// with the default values initialized, and the ability to set a context for a request
func NewJWKSParamsWithContext(ctx context.Context) *JWKSParams {

	return &JWKSParams{

		Context: ctx,
	}
}

// NewJWKSParamsWithHTTPClient creates a new JWKSParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewJWKSParamsWithHTTPClient(client *http.Client) *JWKSParams {

	return &JWKSParams{
		HTTPClient: client,
	}
}

/*JWKSParams contains all the parameters to send to the API endpoint
for the jwks operation typically these are written to a http.Request
*/
type JWKSParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the jwks params
func (o *JWKSParams) WithTimeout(timeout time.Duration) *JWKSParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the jwks params
func (o *JWKSParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the jwks params
func (o *JWKSParams) WithContext(ctx context.Context) *JWKSParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the jwks params
func (o *JWKSParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the jwks params
func (o *JWKSParams) WithHTTPClient(client *http.Client) *JWKSParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the jwks params
func (o *JWKSParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *JWKSParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
