// Code generated by go-swagger; DO NOT EDIT.

package fido_u2f

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/gojans/src/jansAuth/models"
)

// GetFIDOU2FAuthenticationReader is a Reader for the GetFIDOU2FAuthentication structure.
type GetFIDOU2FAuthenticationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFIDOU2FAuthenticationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFIDOU2FAuthenticationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetFIDOU2FAuthenticationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetFIDOU2FAuthenticationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetFIDOU2FAuthenticationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFIDOU2FAuthenticationOK creates a GetFIDOU2FAuthenticationOK with default headers values
func NewGetFIDOU2FAuthenticationOK() *GetFIDOU2FAuthenticationOK {
	return &GetFIDOU2FAuthenticationOK{}
}

/*GetFIDOU2FAuthenticationOK handles this case with default header values.

OK
*/
type GetFIDOU2FAuthenticationOK struct {
	Payload *models.AuthenticateRequestMessage
}

func (o *GetFIDOU2FAuthenticationOK) Error() string {
	return fmt.Sprintf("[GET /fido/u2f/authentication][%d] getFidoU2fAuthenticationOK  %+v", 200, o.Payload)
}

func (o *GetFIDOU2FAuthenticationOK) GetPayload() *models.AuthenticateRequestMessage {
	return o.Payload
}

func (o *GetFIDOU2FAuthenticationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticateRequestMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFIDOU2FAuthenticationForbidden creates a GetFIDOU2FAuthenticationForbidden with default headers values
func NewGetFIDOU2FAuthenticationForbidden() *GetFIDOU2FAuthenticationForbidden {
	return &GetFIDOU2FAuthenticationForbidden{}
}

/*GetFIDOU2FAuthenticationForbidden handles this case with default header values.

Invalid details provided hence access denied.
*/
type GetFIDOU2FAuthenticationForbidden struct {
	Payload *models.ErrorResponse
}

func (o *GetFIDOU2FAuthenticationForbidden) Error() string {
	return fmt.Sprintf("[GET /fido/u2f/authentication][%d] getFidoU2fAuthenticationForbidden  %+v", 403, o.Payload)
}

func (o *GetFIDOU2FAuthenticationForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetFIDOU2FAuthenticationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFIDOU2FAuthenticationNotFound creates a GetFIDOU2FAuthenticationNotFound with default headers values
func NewGetFIDOU2FAuthenticationNotFound() *GetFIDOU2FAuthenticationNotFound {
	return &GetFIDOU2FAuthenticationNotFound{}
}

/*GetFIDOU2FAuthenticationNotFound handles this case with default header values.

Invalid parameters provided to endpoint.
*/
type GetFIDOU2FAuthenticationNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetFIDOU2FAuthenticationNotFound) Error() string {
	return fmt.Sprintf("[GET /fido/u2f/authentication][%d] getFidoU2fAuthenticationNotFound  %+v", 404, o.Payload)
}

func (o *GetFIDOU2FAuthenticationNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetFIDOU2FAuthenticationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFIDOU2FAuthenticationInternalServerError creates a GetFIDOU2FAuthenticationInternalServerError with default headers values
func NewGetFIDOU2FAuthenticationInternalServerError() *GetFIDOU2FAuthenticationInternalServerError {
	return &GetFIDOU2FAuthenticationInternalServerError{}
}

/*GetFIDOU2FAuthenticationInternalServerError handles this case with default header values.

Invalid parameters provided to endpoint.
*/
type GetFIDOU2FAuthenticationInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetFIDOU2FAuthenticationInternalServerError) Error() string {
	return fmt.Sprintf("[GET /fido/u2f/authentication][%d] getFidoU2fAuthenticationInternalServerError  %+v", 500, o.Payload)
}

func (o *GetFIDOU2FAuthenticationInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetFIDOU2FAuthenticationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
