// Code generated by go-swagger; DO NOT EDIT.

package fido_u2f

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/gojans/src/jansAuth/models"
)

// NewPostFIDOU2FAuthenticationParams creates a new PostFIDOU2FAuthenticationParams object
// with the default values initialized.
func NewPostFIDOU2FAuthenticationParams() *PostFIDOU2FAuthenticationParams {
	var ()
	return &PostFIDOU2FAuthenticationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostFIDOU2FAuthenticationParamsWithTimeout creates a new PostFIDOU2FAuthenticationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostFIDOU2FAuthenticationParamsWithTimeout(timeout time.Duration) *PostFIDOU2FAuthenticationParams {
	var ()
	return &PostFIDOU2FAuthenticationParams{

		timeout: timeout,
	}
}

// NewPostFIDOU2FAuthenticationParamsWithContext creates a new PostFIDOU2FAuthenticationParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostFIDOU2FAuthenticationParamsWithContext(ctx context.Context) *PostFIDOU2FAuthenticationParams {
	var ()
	return &PostFIDOU2FAuthenticationParams{

		Context: ctx,
	}
}

// NewPostFIDOU2FAuthenticationParamsWithHTTPClient creates a new PostFIDOU2FAuthenticationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostFIDOU2FAuthenticationParamsWithHTTPClient(client *http.Client) *PostFIDOU2FAuthenticationParams {
	var ()
	return &PostFIDOU2FAuthenticationParams{
		HTTPClient: client,
	}
}

/*PostFIDOU2FAuthenticationParams contains all the parameters to send to the API endpoint
for the post fido u2f authentication operation typically these are written to a http.Request
*/
type PostFIDOU2FAuthenticationParams struct {

	/*Body*/
	Body *models.GetClientTokenParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post fido u2f authentication params
func (o *PostFIDOU2FAuthenticationParams) WithTimeout(timeout time.Duration) *PostFIDOU2FAuthenticationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post fido u2f authentication params
func (o *PostFIDOU2FAuthenticationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post fido u2f authentication params
func (o *PostFIDOU2FAuthenticationParams) WithContext(ctx context.Context) *PostFIDOU2FAuthenticationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post fido u2f authentication params
func (o *PostFIDOU2FAuthenticationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post fido u2f authentication params
func (o *PostFIDOU2FAuthenticationParams) WithHTTPClient(client *http.Client) *PostFIDOU2FAuthenticationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post fido u2f authentication params
func (o *PostFIDOU2FAuthenticationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post fido u2f authentication params
func (o *PostFIDOU2FAuthenticationParams) WithBody(body *models.GetClientTokenParams) *PostFIDOU2FAuthenticationParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post fido u2f authentication params
func (o *PostFIDOU2FAuthenticationParams) SetBody(body *models.GetClientTokenParams) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostFIDOU2FAuthenticationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
