// Code generated by go-swagger; DO NOT EDIT.

package uma2_resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHostRsrcResourceSetRsidParams creates a new GetHostRsrcResourceSetRsidParams object
// with the default values initialized.
func NewGetHostRsrcResourceSetRsidParams() *GetHostRsrcResourceSetRsidParams {
	var ()
	return &GetHostRsrcResourceSetRsidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHostRsrcResourceSetRsidParamsWithTimeout creates a new GetHostRsrcResourceSetRsidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHostRsrcResourceSetRsidParamsWithTimeout(timeout time.Duration) *GetHostRsrcResourceSetRsidParams {
	var ()
	return &GetHostRsrcResourceSetRsidParams{

		timeout: timeout,
	}
}

// NewGetHostRsrcResourceSetRsidParamsWithContext creates a new GetHostRsrcResourceSetRsidParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHostRsrcResourceSetRsidParamsWithContext(ctx context.Context) *GetHostRsrcResourceSetRsidParams {
	var ()
	return &GetHostRsrcResourceSetRsidParams{

		Context: ctx,
	}
}

// NewGetHostRsrcResourceSetRsidParamsWithHTTPClient creates a new GetHostRsrcResourceSetRsidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHostRsrcResourceSetRsidParamsWithHTTPClient(client *http.Client) *GetHostRsrcResourceSetRsidParams {
	var ()
	return &GetHostRsrcResourceSetRsidParams{
		HTTPClient: client,
	}
}

/*GetHostRsrcResourceSetRsidParams contains all the parameters to send to the API endpoint
for the get host rsrc resource set rsid operation typically these are written to a http.Request
*/
type GetHostRsrcResourceSetRsidParams struct {

	/*Authorization
	  Client Authorization details that contains the access token along with other details.

	*/
	Authorization string
	/*Rsid
	  Resource description ID.

	*/
	Rsid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) WithTimeout(timeout time.Duration) *GetHostRsrcResourceSetRsidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) WithContext(ctx context.Context) *GetHostRsrcResourceSetRsidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) WithHTTPClient(client *http.Client) *GetHostRsrcResourceSetRsidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) WithAuthorization(authorization string) *GetHostRsrcResourceSetRsidParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithRsid adds the rsid to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) WithRsid(rsid string) *GetHostRsrcResourceSetRsidParams {
	o.SetRsid(rsid)
	return o
}

// SetRsid adds the rsid to the get host rsrc resource set rsid params
func (o *GetHostRsrcResourceSetRsidParams) SetRsid(rsid string) {
	o.Rsid = rsid
}

// WriteToRequest writes these params to a swagger request
func (o *GetHostRsrcResourceSetRsidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param rsid
	if err := r.SetPathParam("rsid", o.Rsid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
