/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body6 struct {
	// user criterion key (e.g. uid)
	UserCriterionKey string `json:"user_criterion_key"`
	// user criterion value (e.g. chris)
	UserCriterionValue string `json:"user_criterion_value"`
}
