/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body1 struct {
	// OAuth 2.0 Client Identifier valid at the Authorization Server.
	ClientId string `json:"client_id"`
	// CIBA authentication requests must contain the openid scope value.
	Scope string `json:"scope"`
	// It is a bearer token provided by the Client that will be used by the OpenID Provider to authenticate the callback request to the Client. It is required if the Client is registered to use Ping or Push modes.
	ClientNotificationToken string `json:"client_notification_token"`
	// Requested Authentication Context Class Reference values.
	AcrValues string `json:"acr_values,omitempty"`
	// A token containing information identifying the end-user for whom authentication is being requested.
	LoginHintToken string `json:"login_hint_token,omitempty"`
	// An ID Token previously issued to the Client by the OpenID Provider being passed back as a hint to identify the end-user for whom authentication is being requested.
	IdTokenHint string `json:"id_token_hint,omitempty"`
	// A hint to the OpenID Provider regarding the end-user for whom authentication is being requested.
	LoginHint string `json:"login_hint,omitempty"`
	// A human readable identifier or message intended to be displayed on both the consumption device and the authentication device to interlock them together for the transaction by way of a visual cue for the end-user.
	BindingMessage string `json:"binding_message,omitempty"`
	// A secret code, such as password or pin, known only to the user but verifiable by the OP.
	UserCode string `json:"user_code,omitempty"`
	// A positive integer allowing the client to request the expires_in value for the auth_req_id the server will return.
	RequestedExpiry int32 `json:"requested_expiry,omitempty"`
}
