/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An object containing various options for the option creation
type AttestationOptions1 struct {
	Type_ string `json:"type,omitempty"`
	// The base64url encoded clientDataJSON returned by the client
	ClientDataJSON []string `json:"clientDataJSON"`
	Id string `json:"id,omitempty"`
}
