/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// FIDO U2F device authentication status.
type AuthenticateStatus struct {
	// Version of the protocol that the to-be-registered U2F token must speak.
	Status string `json:"status"`
	// The websafe-base64-encoded challenge.
	Challenge string `json:"challenge"`
}
