/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body struct {
	// OpenID Connect requests MUST contain the openid scope value. If the openid scope value is not present, the behavior is entirely unspecified. Other scope values MAY be present.
	Scope string `json:"scope"`
	// OAuth 2.0 Response Type value that determines the authorization processing flow to be used, including what parameters are returned from the endpoints used.
	ResponseType string `json:"response_type"`
	// OAuth 2.0 Client Identifier valid at the Authorization Server.
	ClientId string `json:"client_id"`
	// Redirection URI to which the response will be sent. This URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider.
	RedirectUri string `json:"redirect_uri"`
	// Opaque value used to maintain state between the request and the callback.
	State string `json:"state,omitempty"`
	// Informs the Authorization Server of the mechanism to be used for returning parameters from the Authorization Endpoint.
	ResponseMode string `json:"response_mode,omitempty"`
	// String value used to associate a Client session with an ID Token, and to mitigate replay attacks.
	Nonce string `json:"nonce,omitempty"`
	// ASCII string value that specifies how the Authorization Server displays the authentication and consent user interface pages to the End-User.
	Display string `json:"display,omitempty"`
	// Space delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent.
	Prompt string `json:"prompt,omitempty"`
	// Maximum Authentication Age. Specifies the allowable elapsed time in seconds since the last time the End-User was actively authenticated by the OP.
	MaxAge int32 `json:"max_age,omitempty"`
	// End-User's preferred languages and scripts for the user interface, represented as a space-separated list of BCP47 [RFC5646] language tag values, ordered by preference.
	UiLocales string `json:"ui_locales,omitempty"`
	// ID Token previously issued by the Authorization Server being passed as a hint about the End-User's current or past authenticated session with the Client. If the End-User identified by the ID Token is logged in or is logged in by the request, then the Authorization Server returns a positive response.
	IdTokenHint string `json:"id_token_hint,omitempty"`
	// Hint to the Authorization Server about the login identifier the End-User might use to log in (if necessary).
	LoginHint string `json:"login_hint,omitempty"`
	// Requested Authentication Context Class Reference values. Space-separated string that specifies the acr values that the Authorization Server is being requested to use for processing this Authentication Request, with the values appearing in order of preference.
	AcrValues string `json:"acr_values,omitempty"`
	// AMR Values.
	AmrValues string `json:"amr_values,omitempty"`
	// This parameter enables OpenID Connect requests to be passed in a single, self-contained parameter and to be optionally signed and/or encrypted. The parameter value is a Request Object value. It represents the request as a JWT whose Claims are the request parameters.
	Request string `json:"request,omitempty"`
	// This parameter enables OpenID Connect requests to be passed by reference, rather than by value. The request_uri value is a URL using the https scheme referencing a resource containing a Request Object value, which is a JWT containing the request parameters.
	RequestUri string `json:"request_uri,omitempty"`
	// Request session id.
	RequestSessionId string `json:"request_session_id,omitempty"`
	// Session id of this call.
	SessionId string `json:"session_id,omitempty"`
	// Origin headers. Used in custom workflows.
	OriginHeaders string `json:"origin_headers,omitempty"`
	// PKCE code challenge.
	CodeChallenge string `json:"code_challenge,omitempty"`
	// PKCE code challenge method.
	CodeChallengeMethod string `json:"code_challenge_method,omitempty"`
	// Custom Response Headers.
	CustomResponseHeaders string `json:"custom_response_headers,omitempty"`
	// Requested Claims.
	Claims string `json:"claims,omitempty"`
}
