/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body7 struct {
	// Provide a list of the OAuth 2.0 grant types that the Client is declaring that it will restrict itself to using.
	GrantType []string `json:"grant_type"`
	// Code which is returned by authorization endpoint. (For grant_type=authorization_code)
	Code string `json:"code,omitempty"`
	// Redirection URI to which the response will be sent. This URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider.
	RedirectUri string `json:"redirect_uri,omitempty"`
	// End-User username.
	Username string `json:"username,omitempty"`
	// End-User password.
	Password string `json:"password,omitempty"`
	// OpenID Connect requests MUST contain the openid scope value. If the openid scope value is not present, the behavior is entirely unspecified. Other scope values MAY be present. Scope values used that are not understood by an implementation SHOULD be ignored.
	Scope []string `json:"scope,omitempty"`
	// Assertion.
	Assertion string `json:"assertion,omitempty"`
	// Refresh token.
	RefreshToken string `json:"refresh_token,omitempty"`
	// OAuth 2.0 Client Identifier valid at the Authorization Server.
	ClientId string `json:"client_id,omitempty"`
	// The client secret.  The client MAY omit the parameter if the client secret is an empty string.
	ClientSecret string `json:"client_secret,omitempty"`
	// The client's PKCE code verifier.
	CodeVerifier string `json:"code_verifier,omitempty"`
	Ticket string `json:"ticket,omitempty"`
	ClaimToken string `json:"claim_token,omitempty"`
	ClaimTokenFormat string `json:"claim_token_format,omitempty"`
	Pct string `json:"pct,omitempty"`
	Rpt string `json:"rpt,omitempty"`
}
