/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Uma Resource details
type UmaResourceWithId struct {
	// UMA Resource identifier
	Id string `json:"_id"`
	// A human-readable string describing a set of one or more resources. This name MAY be used by the authorization server in its resource owner user interface for the resource owner.
	Name string `json:"name,omitempty"`
	// A human-readable string describing the resource
	Uri string `json:"uri,omitempty"`
	// A string uniquely identifying the semantics of the resource set. For example, if the resource set consists of a single resource that is an identity claim that leverages standardized claim semantics for \\\"verified email address\\\", the value of this property could be an identifying URI for this claim.
	Type_ string `json:"type,omitempty"`
	// An array of strings, any of which MAY be a URI, indicating the available scopes for this resource set. URIs MUST resolve to scope descriptions as defined in Section 2.1. Published scope descriptions MAY reside anywhere on the web; a resource server is not required to self-host scope descriptions and may wish to point to standardized scope descriptions residing elsewhere. It is the resource server's responsibility to ensure that scope description documents are accessible to authorization servers through GET calls to support any user interface requirements. The resource server and authorization server are presumed to have separately negotiated any required interpretation of scope handling not conveyed through scope descriptions.
	Scopes []string `json:"scopes,omitempty"`
	ScopeExpression string `json:"scope_expression,omitempty"`
	// A human-readable string describing the resource
	Description string `json:"description,omitempty"`
	// A URI for a graphic icon representing the resource set. The referenced icon MAY be used by the authorization server in its resource owner user interface for the resource owner.
	IconUri string `json:"icon_uri,omitempty"`
	// number of seconds since January 1 1970 UTC, indicating when the token was issued at
	Iat int64 `json:"iat"`
	// number of seconds since January 1 1970 UTC, indicating when this token will expire.
	Exp int64 `json:"exp"`
}
