/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// FIDO2 configuration.
type Fido2Configuration struct {
	// The version of the FIDO2 U2F core protocol to which this server conforms. The value MUST be the string 1.0.
	Version string `json:"version"`
	// A URI indicating the party operating the FIDO U2F server.
	Issuer string `json:"issuer"`
	Attestation []Fido2ConfigurationAttestation `json:"attestation"`
	Assertion []Fido2ConfigurationAssertion `json:"assertion,omitempty"`
}
