/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// RegisterRequestMessage
type RegisterStatus struct {
	Status string `json:"status,omitempty"`
	Challenge string `json:"challenge,omitempty"`
}
