/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SessionStateObject struct {
	// String that represents the End-User's login state at the OP. It MUST NOT contain the space (\\\" \\\") character.
	State string `json:"state,omitempty"`
	// specifies the time at which session was authenticated.
	AuthTime string `json:"auth_time,omitempty"`
	CustomState string `json:"custom_state,omitempty"`
}
