/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AssertionOptions1 struct {
	// The base64url encoded id returned by the client
	Id string `json:"id,omitempty"`
	Type_ []string `json:"type,omitempty"`
	// The base64url encoded rawId returned by the client. If res.rawId is missing, res.id will be used instead. If both are missing an error will be thrown.
	RawId string `json:"rawId,omitempty"`
	// The base64url encoded userHandle returned by the client. May be null or an empty string.
	UserHandle string `json:"userHandle,omitempty"`
	// The base64url encoded clientDataJSON returned by the client
	ClientDataJSON []string `json:"clientDataJSON"`
}
