/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CredentialCreationOptions struct {
	// The base64url encoded challenge that was sent to the client, as generated by assertionOptions.
	Challenge string `json:"challenge"`
	// RP credentials
	Rp []string `json:"rp"`
	User *CredentialCreationOptionsUser `json:"user"`
	Attestation string `json:"attestation"`
	PubKeyCredParams []string `json:"pubKeyCredParams"`
	AuthenticatorSelection []string `json:"authenticatorSelection"`
	ExcludeCredentials []string `json:"excludeCredentials"`
	Extensions string `json:"extensions"`
}
