/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// AccessTokenResponse.
type InlineResponse200 struct {
	// The access token issued by the authorization server.
	AccessToken string `json:"access_token"`
	// The access token type provides the client with the information required to successfully utilize the access token to make a protected resource request (along with type-specific attributes).
	TokenType string `json:"token_type"`
	// The lifetime in seconds of the access token. For example, the value \\\"3600\\\" denotes that the access token will expire in one hour from the time the response was generated.
	ExpiresIn int32 `json:"expires_in,omitempty"`
	// The refresh token, which can be used to obtain new access tokens using the same authorization grant
	RefreshToken string `json:"refresh_token,omitempty"`
	Scope []string `json:"scope,omitempty"`
	IdToken string `json:"id_token,omitempty"`
}
