/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type JsonWebKey struct {
	Kid string `json:"kid"`
	Kty string `json:"kty"`
	Use string `json:"use"`
	Alg string `json:"alg"`
	Crv string `json:"crv,omitempty"`
	Exp int64 `json:"exp"`
	X5c []string `json:"x5c"`
	N string `json:"n,omitempty"`
	E string `json:"e,omitempty"`
	X string `json:"x,omitempty"`
	Y string `json:"y,omitempty"`
}
