/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// list of fido2 attestation endpoints
type Fido2ConfigurationAttestation struct {
	// fido2 attestation endpoint
	BasePath string `json:"base_path,omitempty"`
	// fido2 attestation options endpoint
	OptionsEnpoint string `json:"options_enpoint,omitempty"`
	// fido2 attestation result endpoint
	ResultEnpoint string `json:"result_enpoint,omitempty"`
}
