/*
 * oxAuth
 *
 * oxAuth - OAuth 2.0 server; OpenID Connect Provider (OP) & UMA Authorization Server (AS)
 *
 * API version: 4.2
 * Contact: yuriyz@gluu.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body8 struct {
	// OAuth 2.0 Client Identifier valid at the Authorization Server.
	ClientId string `json:"client_id,omitempty"`
	Ticket string `json:"ticket,omitempty"`
	ClaimsRedirectUri string `json:"claims_redirect_uri,omitempty"`
	State string `json:"state,omitempty"`
	Reset bool `json:"reset,omitempty"`
	Authentication bool `json:"authentication,omitempty"`
}
