// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Assertion Assertion
//
// list of fido2 assertion endpoints
//
// swagger:model Assertion
type Assertion struct {

	// fido2 assertion endpoint
	BasePath string `json:"base_path,omitempty"`

	// fido2 assertion options endpoint
	OptionsEnpoint string `json:"options_enpoint,omitempty"`

	// fido2 assertion result endpoint
	ResultEnpoint string `json:"result_enpoint,omitempty"`
}

// Validate validates this assertion
func (m *Assertion) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Assertion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Assertion) UnmarshalBinary(b []byte) error {
	var res Assertion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
