// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthenticateRequest AuthenticateRequest
//
// list of AuthenticateRequest
//
// swagger:model AuthenticateRequest
type AuthenticateRequest struct {

	// The application id that the RP would like to assert.
	AppID string `json:"appId,omitempty"`

	// The websafe-base64-encoded challenge.
	Challenge string `json:"challenge,omitempty"`

	// websafe-base64 encoding of the key handle obtained from the U2F token during registration
	KeyHandle string `json:"keyHandle,omitempty"`

	// Version of the protocol that the to-be-registered U2F token must speak.
	Version string `json:"version,omitempty"`
}

// Validate validates this authenticate request
func (m *AuthenticateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthenticateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthenticateRequest) UnmarshalBinary(b []byte) error {
	var res AuthenticateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
