// Code generated by go-swagger; DO NOT EDIT.

package server_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new server configuration API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for server configuration API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	WellKnownGluuConfiguration(params *WellKnownGluuConfigurationParams) (*WellKnownGluuConfigurationOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  WellKnownGluuConfiguration wells known gluu configuration

  Gets GluuServer configuration data that contains non-standard OpenID Connect discovery metadata.
*/
func (a *Client) WellKnownGluuConfiguration(params *WellKnownGluuConfigurationParams) (*WellKnownGluuConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewWellKnownGluuConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "well-known-gluu-configuration",
		Method:             "POST",
		PathPattern:        "/.well-known/gluu-configuration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WellKnownGluuConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*WellKnownGluuConfigurationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for well-known-gluu-configuration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
