// Code generated by go-swagger; DO NOT EDIT.

package server_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWellKnownGluuConfigurationParams creates a new WellKnownGluuConfigurationParams object
// with the default values initialized.
func NewWellKnownGluuConfigurationParams() *WellKnownGluuConfigurationParams {

	return &WellKnownGluuConfigurationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWellKnownGluuConfigurationParamsWithTimeout creates a new WellKnownGluuConfigurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWellKnownGluuConfigurationParamsWithTimeout(timeout time.Duration) *WellKnownGluuConfigurationParams {

	return &WellKnownGluuConfigurationParams{

		timeout: timeout,
	}
}

// NewWellKnownGluuConfigurationParamsWithContext creates a new WellKnownGluuConfigurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewWellKnownGluuConfigurationParamsWithContext(ctx context.Context) *WellKnownGluuConfigurationParams {

	return &WellKnownGluuConfigurationParams{

		Context: ctx,
	}
}

// NewWellKnownGluuConfigurationParamsWithHTTPClient creates a new WellKnownGluuConfigurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWellKnownGluuConfigurationParamsWithHTTPClient(client *http.Client) *WellKnownGluuConfigurationParams {

	return &WellKnownGluuConfigurationParams{
		HTTPClient: client,
	}
}

/*WellKnownGluuConfigurationParams contains all the parameters to send to the API endpoint
for the well known gluu configuration operation typically these are written to a http.Request
*/
type WellKnownGluuConfigurationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the well known gluu configuration params
func (o *WellKnownGluuConfigurationParams) WithTimeout(timeout time.Duration) *WellKnownGluuConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the well known gluu configuration params
func (o *WellKnownGluuConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the well known gluu configuration params
func (o *WellKnownGluuConfigurationParams) WithContext(ctx context.Context) *WellKnownGluuConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the well known gluu configuration params
func (o *WellKnownGluuConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the well known gluu configuration params
func (o *WellKnownGluuConfigurationParams) WithHTTPClient(client *http.Client) *WellKnownGluuConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the well known gluu configuration params
func (o *WellKnownGluuConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *WellKnownGluuConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
