// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AttestationOptions AttestationOptions
//
// An object containing various options for the option creation
//
// swagger:model AttestationOptions
type AttestationOptions struct {

	// authenticator selection
	AuthenticatorSelection []string `json:"authenticatorSelection"`

	// credential type
	CredentialType string `json:"credentialType,omitempty"`

	// display name
	DisplayName string `json:"displayName,omitempty"`

	// document domain
	DocumentDomain string `json:"documentDomain,omitempty"`

	// extensions
	Extensions string `json:"extensions,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this attestation options
func (m *AttestationOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AttestationOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AttestationOptions) UnmarshalBinary(b []byte) error {
	var res AttestationOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
