// Code generated by go-swagger; DO NOT EDIT.

package uma_2_resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/gojans/src/jansAuth/models"
)

// DeleteHostRsrcResourceSetReader is a Reader for the DeleteHostRsrcResourceSet structure.
type DeleteHostRsrcResourceSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHostRsrcResourceSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteHostRsrcResourceSetNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteHostRsrcResourceSetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteHostRsrcResourceSetNoContent creates a DeleteHostRsrcResourceSetNoContent with default headers values
func NewDeleteHostRsrcResourceSetNoContent() *DeleteHostRsrcResourceSetNoContent {
	return &DeleteHostRsrcResourceSetNoContent{}
}

/*DeleteHostRsrcResourceSetNoContent handles this case with default header values.

OK
*/
type DeleteHostRsrcResourceSetNoContent struct {
}

func (o *DeleteHostRsrcResourceSetNoContent) Error() string {
	return fmt.Sprintf("[DELETE /host/rsrc/resource_set][%d] deleteHostRsrcResourceSetNoContent ", 204)
}

func (o *DeleteHostRsrcResourceSetNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHostRsrcResourceSetInternalServerError creates a DeleteHostRsrcResourceSetInternalServerError with default headers values
func NewDeleteHostRsrcResourceSetInternalServerError() *DeleteHostRsrcResourceSetInternalServerError {
	return &DeleteHostRsrcResourceSetInternalServerError{}
}

/*DeleteHostRsrcResourceSetInternalServerError handles this case with default header values.

Invalid parameters provided to endpoint.
*/
type DeleteHostRsrcResourceSetInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *DeleteHostRsrcResourceSetInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /host/rsrc/resource_set][%d] deleteHostRsrcResourceSetInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteHostRsrcResourceSetInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteHostRsrcResourceSetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
