// Code generated by go-swagger; DO NOT EDIT.

package uma_2_resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/gojans/pkg/jansAuth/models"
)

// PostHostRsrcResourceSetReader is a Reader for the PostHostRsrcResourceSet structure.
type PostHostRsrcResourceSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostHostRsrcResourceSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostHostRsrcResourceSetCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostHostRsrcResourceSetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostHostRsrcResourceSetCreated creates a PostHostRsrcResourceSetCreated with default headers values
func NewPostHostRsrcResourceSetCreated() *PostHostRsrcResourceSetCreated {
	return &PostHostRsrcResourceSetCreated{}
}

/*PostHostRsrcResourceSetCreated handles this case with default header values.

OK
*/
type PostHostRsrcResourceSetCreated struct {
	Payload *models.UMAResourceResponse
}

func (o *PostHostRsrcResourceSetCreated) Error() string {
	return fmt.Sprintf("[POST /host/rsrc/resource_set][%d] postHostRsrcResourceSetCreated  %+v", 201, o.Payload)
}

func (o *PostHostRsrcResourceSetCreated) GetPayload() *models.UMAResourceResponse {
	return o.Payload
}

func (o *PostHostRsrcResourceSetCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UMAResourceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostHostRsrcResourceSetInternalServerError creates a PostHostRsrcResourceSetInternalServerError with default headers values
func NewPostHostRsrcResourceSetInternalServerError() *PostHostRsrcResourceSetInternalServerError {
	return &PostHostRsrcResourceSetInternalServerError{}
}

/*PostHostRsrcResourceSetInternalServerError handles this case with default header values.

Invalid parameters provided to endpoint.
*/
type PostHostRsrcResourceSetInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PostHostRsrcResourceSetInternalServerError) Error() string {
	return fmt.Sprintf("[POST /host/rsrc/resource_set][%d] postHostRsrcResourceSetInternalServerError  %+v", 500, o.Payload)
}

func (o *PostHostRsrcResourceSetInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostHostRsrcResourceSetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
