/*
 * oxauth_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package clientregistration_pkg

import "oxauth_lib/configuration_pkg"

/*
 * Interface for the CLIENTREGISTRATION_IMPL
 */
type CLIENTREGISTRATION interface {
    DeleteRegister (string, string) (error)
}

/*
 * Factory for the CLIENTREGISTRATION interaface returning CLIENTREGISTRATION_IMPL
 */
func NewCLIENTREGISTRATION(config configuration_pkg.CONFIGURATION) *CLIENTREGISTRATION_IMPL {
    client := new(CLIENTREGISTRATION_IMPL)
    client.config = config
    return client
}