// Code generated by go-swagger; DO NOT EDIT.

package registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new registration API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for registration API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	BcDeviceRegistration(params *BcDeviceRegistrationParams) (*BcDeviceRegistrationOK, error)

	GetRegister(params *GetRegisterParams) (*GetRegisterOK, error)

	PostRegister(params *PostRegisterParams) (*PostRegisterOK, error)

	PutRegister(params *PutRegisterParams) (*PutRegisterOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  BcDeviceRegistration bcs device registration

  Performs backchannel device registration.
*/
func (a *Client) BcDeviceRegistration(params *BcDeviceRegistrationParams) (*BcDeviceRegistrationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewBcDeviceRegistrationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "bc-deviceRegistration",
		Method:             "POST",
		PathPattern:        "/bc-deviceRegistration",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &BcDeviceRegistrationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*BcDeviceRegistrationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for bc-deviceRegistration: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetRegister gets register

  Get client information for a previously registered client.
*/
func (a *Client) GetRegister(params *GetRegisterParams) (*GetRegisterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRegisterParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get-register",
		Method:             "GET",
		PathPattern:        "/register",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRegisterReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRegisterOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for get-register: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostRegister posts register

  The Client Registration Endpoint is an OAuth 2.0 Protected Resource through which a new Client registration can be requested.
*/
func (a *Client) PostRegister(params *PostRegisterParams) (*PostRegisterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostRegisterParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "post-register",
		Method:             "POST",
		PathPattern:        "/register",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostRegisterReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostRegisterOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for post-register: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PutRegister puts register

  Update Client Metadata for a registered client.
*/
func (a *Client) PutRegister(params *PutRegisterParams) (*PutRegisterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutRegisterParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "put-register",
		Method:             "PUT",
		PathPattern:        "/register",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PutRegisterReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutRegisterOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for put-register: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
