// Code generated by go-swagger; DO NOT EDIT.

package session_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSessionStatusParams creates a new SessionStatusParams object
// with the default values initialized.
func NewSessionStatusParams() *SessionStatusParams {

	return &SessionStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSessionStatusParamsWithTimeout creates a new SessionStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSessionStatusParamsWithTimeout(timeout time.Duration) *SessionStatusParams {

	return &SessionStatusParams{

		timeout: timeout,
	}
}

// NewSessionStatusParamsWithContext creates a new SessionStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewSessionStatusParamsWithContext(ctx context.Context) *SessionStatusParams {

	return &SessionStatusParams{

		Context: ctx,
	}
}

// NewSessionStatusParamsWithHTTPClient creates a new SessionStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSessionStatusParamsWithHTTPClient(client *http.Client) *SessionStatusParams {

	return &SessionStatusParams{
		HTTPClient: client,
	}
}

/*SessionStatusParams contains all the parameters to send to the API endpoint
for the session status operation typically these are written to a http.Request
*/
type SessionStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the session status params
func (o *SessionStatusParams) WithTimeout(timeout time.Duration) *SessionStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the session status params
func (o *SessionStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the session status params
func (o *SessionStatusParams) WithContext(ctx context.Context) *SessionStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the session status params
func (o *SessionStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the session status params
func (o *SessionStatusParams) WithHTTPClient(client *http.Client) *SessionStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the session status params
func (o *SessionStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SessionStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
