// Code generated by go-swagger; DO NOT EDIT.

package session_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/gojans/pkg/jansAuth/models"
)

// SessionStatusReader is a Reader for the SessionStatus structure.
type SessionStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SessionStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSessionStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSessionStatusOK creates a SessionStatusOK with default headers values
func NewSessionStatusOK() *SessionStatusOK {
	return &SessionStatusOK{}
}

/*SessionStatusOK handles this case with default header values.

OK
*/
type SessionStatusOK struct {
	Payload *models.SessionStateObject
}

func (o *SessionStatusOK) Error() string {
	return fmt.Sprintf("[GET /session_status][%d] sessionStatusOK  %+v", 200, o.Payload)
}

func (o *SessionStatusOK) GetPayload() *models.SessionStateObject {
	return o.Payload
}

func (o *SessionStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SessionStateObject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
