/*
 * oxauth_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package umascope_pkg

import "oxauth_lib/configuration_pkg"
import "oxauth_lib/models_pkg"

/*
 * Interface for the UMASCOPE_IMPL
 */
type UMASCOPE interface {
    GetUmaScopes (string) (*models_pkg.UmaScopeDescription, error)
}

/*
 * Factory for the UMASCOPE interaface returning UMASCOPE_IMPL
 */
func NewUMASCOPE(config configuration_pkg.CONFIGURATION) *UMASCOPE_IMPL {
    client := new(UMASCOPE_IMPL)
    client.config = config
    return client
}