// Code generated by go-swagger; DO NOT EDIT.

package server_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/gojans/src/jansAuth/models"
)

// WellKnownGluuConfigurationReader is a Reader for the WellKnownGluuConfiguration structure.
type WellKnownGluuConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WellKnownGluuConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWellKnownGluuConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewWellKnownGluuConfigurationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWellKnownGluuConfigurationOK creates a WellKnownGluuConfigurationOK with default headers values
func NewWellKnownGluuConfigurationOK() *WellKnownGluuConfigurationOK {
	return &WellKnownGluuConfigurationOK{}
}

/*WellKnownGluuConfigurationOK handles this case with default header values.

OK
*/
type WellKnownGluuConfigurationOK struct {
	Payload *models.GluuConfigurationResponse
}

func (o *WellKnownGluuConfigurationOK) Error() string {
	return fmt.Sprintf("[POST /.well-known/gluu-configuration][%d] wellKnownGluuConfigurationOK  %+v", 200, o.Payload)
}

func (o *WellKnownGluuConfigurationOK) GetPayload() *models.GluuConfigurationResponse {
	return o.Payload
}

func (o *WellKnownGluuConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GluuConfigurationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWellKnownGluuConfigurationInternalServerError creates a WellKnownGluuConfigurationInternalServerError with default headers values
func NewWellKnownGluuConfigurationInternalServerError() *WellKnownGluuConfigurationInternalServerError {
	return &WellKnownGluuConfigurationInternalServerError{}
}

/*WellKnownGluuConfigurationInternalServerError handles this case with default header values.

Internal error occured. Please check log file for details.
*/
type WellKnownGluuConfigurationInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *WellKnownGluuConfigurationInternalServerError) Error() string {
	return fmt.Sprintf("[POST /.well-known/gluu-configuration][%d] wellKnownGluuConfigurationInternalServerError  %+v", 500, o.Payload)
}

func (o *WellKnownGluuConfigurationInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *WellKnownGluuConfigurationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
