/*
 * oxauth_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package OxAuthClient

import(
	"oxauth_lib/configuration_pkg"
	"oxauth_lib/authorization_pkg"
	"oxauth_lib/registration_pkg"
	"oxauth_lib/clientinfo_pkg"
	"oxauth_lib/serverconfiguration_pkg"
	"oxauth_lib/token_pkg"
	"oxauth_lib/jwkjsonwebkeysetjwks_pkg"
	"oxauth_lib/clientregistration_pkg"
	"oxauth_lib/sessionmanagement_pkg"
	"oxauth_lib/umausermanagedaccess_pkg"
	"oxauth_lib/uma2resource_pkg"
	"oxauth_lib/tokenintrospection_pkg"
	"oxauth_lib/umascope_pkg"
	"oxauth_lib/userinfo_pkg"
	"oxauth_lib/fidou2f_pkg"
	"oxauth_lib/fido2_pkg"
)


/*
 * Interface for the OXAUTH_IMPL
 */
type OXAUTH interface {
    Authorization()         authorization_pkg.AUTHORIZATION
    Registration()          registration_pkg.REGISTRATION
    ClientInfo()            clientinfo_pkg.CLIENTINFO
    ServerConfiguration()       serverconfiguration_pkg.SERVERCONFIGURATION
    Token()                 token_pkg.TOKEN
    JWKJSONWebKeySetJWKs()       jwkjsonwebkeysetjwks_pkg.JWKJSONWEBKEYSETJWKS
    ClientRegistration()       clientregistration_pkg.CLIENTREGISTRATION
    SessionManagement()       sessionmanagement_pkg.SESSIONMANAGEMENT
    UMAUserManagedAccess()       umausermanagedaccess_pkg.UMAUSERMANAGEDACCESS
    UMA2Resource()          uma2resource_pkg.UMA2RESOURCE
    TokenIntrospection()       tokenintrospection_pkg.TOKENINTROSPECTION
    UMAScope()              umascope_pkg.UMASCOPE
    UserInfo()              userinfo_pkg.USERINFO
    FIDOU2F()               fidou2f_pkg.FIDOU2F
    FIDO2()                 fido2_pkg.FIDO2
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the OXAUTH interface returning OXAUTH_IMPL
 */
func NewOXAUTH() OXAUTH {
    oxAuthClient := new(OXAUTH_IMPL)
    oxAuthClient.config = configuration_pkg.NewCONFIGURATION()

    return oxAuthClient
}
