// Code generated by go-swagger; DO NOT EDIT.

package fido2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/gojans/src/jansAuth/models"
)

// NewAttestationOptionsParams creates a new AttestationOptionsParams object
// with the default values initialized.
func NewAttestationOptionsParams() *AttestationOptionsParams {
	var ()
	return &AttestationOptionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAttestationOptionsParamsWithTimeout creates a new AttestationOptionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAttestationOptionsParamsWithTimeout(timeout time.Duration) *AttestationOptionsParams {
	var ()
	return &AttestationOptionsParams{

		timeout: timeout,
	}
}

// NewAttestationOptionsParamsWithContext creates a new AttestationOptionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewAttestationOptionsParamsWithContext(ctx context.Context) *AttestationOptionsParams {
	var ()
	return &AttestationOptionsParams{

		Context: ctx,
	}
}

// NewAttestationOptionsParamsWithHTTPClient creates a new AttestationOptionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAttestationOptionsParamsWithHTTPClient(client *http.Client) *AttestationOptionsParams {
	var ()
	return &AttestationOptionsParams{
		HTTPClient: client,
	}
}

/*AttestationOptionsParams contains all the parameters to send to the API endpoint
for the attestation options operation typically these are written to a http.Request
*/
type AttestationOptionsParams struct {

	/*Body*/
	Body *models.AttestationOptions

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the attestation options params
func (o *AttestationOptionsParams) WithTimeout(timeout time.Duration) *AttestationOptionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the attestation options params
func (o *AttestationOptionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the attestation options params
func (o *AttestationOptionsParams) WithContext(ctx context.Context) *AttestationOptionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the attestation options params
func (o *AttestationOptionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the attestation options params
func (o *AttestationOptionsParams) WithHTTPClient(client *http.Client) *AttestationOptionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the attestation options params
func (o *AttestationOptionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the attestation options params
func (o *AttestationOptionsParams) WithBody(body *models.AttestationOptions) *AttestationOptionsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the attestation options params
func (o *AttestationOptionsParams) SetBody(body *models.AttestationOptions) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AttestationOptionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
