/*
 * oxauth_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package tokenintrospection_pkg

import "oxauth_lib/configuration_pkg"
import "oxauth_lib/models_pkg"

/*
 * Interface for the TOKENINTROSPECTION_IMPL
 */
type TOKENINTROSPECTION interface {
    GetRptStatus (string, string, *string) (*models_pkg.RptIntrospectionResponse, error)

    PostRptStatus (string, string, *string) (*models_pkg.RptIntrospectionResponse1, error)
}

/*
 * Factory for the TOKENINTROSPECTION interaface returning TOKENINTROSPECTION_IMPL
 */
func NewTOKENINTROSPECTION(config configuration_pkg.CONFIGURATION) *TOKENINTROSPECTION_IMPL {
    client := new(TOKENINTROSPECTION_IMPL)
    client.config = config
    return client
}